title: Josh Website 
author: Josue Salazar 
logo: /assets/img/logo.png
description: This is a project intended to show my work that Ive done as a part of my Computer Science Degree  
google_analytics:
theme: jekyll-theme-minimal
